// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function() {
    var root, useHash;
    root = null;
    useHash = true;
    window._router = new Navigo(root, useHash);
    window._pageManager = new ProTrumpAntiTrumpManager();
    return window._router.on({
      '/uk/bubble': function() {
        return _pageManager.setup('uk', 'bubble');
      },
      '/uk/table': function() {
        return _pageManager.setup('uk', 'table');
      },
      '/non-uk/bubble': function() {
        return _pageManager.setup('non-uk', 'bubble');
      },
      '/non-uk/table': function() {
        return _pageManager.setup('non-uk', 'table');
      },
      '/bubble': function() {
        return window._router.navigate('/non-uk/bubble');
      },
      '/uk': function() {
        return window._router.navigate('/uk/table');
      },
      '/': function() {
        return window._router.navigate('/non-uk/table');
      }
    }).resolve();
  });

}).call(this);

//# sourceMappingURL=_initProTrumpAntiTrump.js.map
