// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function() {
    window._pageManager = new PageManager("https://petition.parliament.uk/petitions/171928.json");
    return window._pageManager.setup();
  });

}).call(this);

//# sourceMappingURL=_init.js.map
