// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function() {
    return PageManager.setup("https://petition.parliament.uk/petitions/171928.json");
  });

}).call(this);

//# sourceMappingURL=_init.js.map
