// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function() {
    window._proTrumpAntiTrumpManager = new ProTrumpAntiTrumpManager();
    return window._proTrumpAntiTrumpManager.setup('non-uk');
  });

}).call(this);

//# sourceMappingURL=_initProTrumpAntiTrump.js.map
