// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function() {
    var DEFAULT_TO_TRUMP_OR_NO_FUNDING, root, useHash;
    root = null;
    useHash = true;
    window._router = new Navigo(root, useHash);
    window._pageManager = new PageManager(window._router);
    window._router.on({
      '/petitions/:id/uk': function(params) {
        return _pageManager.navigateToPetition(params.id, 'uk');
      },
      '/petitions/:id': function(params) {
        return _pageManager.navigateToPetition(params.id);
      }
    }).resolve();
    DEFAULT_TO_TRUMP_OR_NO_FUNDING = "/petitions/171928";
    if (!window._pageManager.arrivedDirectlyAtAPetition) {
      return window._router.navigate(DEFAULT_TO_TRUMP_OR_NO_FUNDING);
    }
  });

}).call(this);

//# sourceMappingURL=_init.js.map
