// Generated by CoffeeScript 1.9.3
(function() {
  var Chart, setupTitle,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Chart = (function() {
    function Chart(petitionData1) {
      this.petitionData = petitionData1;
      this.draw = bind(this.draw, this);
      this.countryLabels = this.petitionData.signaturesByCountryDescendingCount().map(function(country) {
        return country.name;
      });
      this.data = this.petitionData.signaturesByCountryDescendingCount().map(function(country) {
        return country.signature_count;
      });
    }

    Chart.prototype.draw = function() {
      var bar, barWidth, height, margin, svg, width, x, xAxis, y, yAxis;
      margin = {
        top: 40,
        right: 70,
        bottom: 150,
        left: 70
      };
      width = window.innerWidth - margin.left - margin.right;
      height = 550 - margin.top - margin.bottom;
      barWidth = width / this.data.length;
      x = d3.scale.ordinal().domain(this.countryLabels).rangeBands([0, width]);
      y = d3.scale.linear().domain([0, this.petitionData.maxCountryFrequency()]).range([height, 0]);
      xAxis = d3.svg.axis().scale(x).orient("bottom");
      yAxis = d3.svg.axis().scale(y).orient("left");
      svg = d3.select("#chart").append("svg").attr("width", width + margin.left + margin.right).attr("height", height + margin.top + margin.bottom).append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");
      svg.append("g").attr("class", "x axis").attr("transform", "translate(0," + height + ")").call(xAxis).selectAll("text").attr("transform", "rotate(90)").attr("x", 15).attr("y", 0).style("text-anchor", "start");
      svg.append("g").attr("class", "y axis").call(yAxis).append("text").attr("transform", "rotate(-90)").attr("y", -63).attr("dy", ".71em").style("text-anchor", "end").text("Signatures");
      bar = svg.selectAll(".bar").data(this.data).enter().append("rect").attr("class", "bar").attr("width", barWidth - 1).attr("height", function(d) {
        return height - y(d);
      }).attr("x", function(d, i) {
        return i * barWidth;
      }).attr("y", function(d) {
        return y(d);
      });
      return bar.append("rect");
    };

    return Chart;

  })();

  setupTitle = function(petitionData) {
    var formattedSignatureCount;
    $('.petition-title').text(petitionData.title());
    formattedSignatureCount = petitionData.uk().signature_count.toLocaleString('en-GB', {
      minimumFractionDigits: 0
    });
    return $('.uk-signatures').text("(" + formattedSignatureCount + " UK signatures)");
  };

  jQuery(function() {
    if (document.getElementById('chart')) {
      return $.ajax({
        url: "https://petition.parliament.uk/petitions/171928.json",
        dataType: "json",
        error: function(jqXHR, textStatus, errorThrown) {
          return console.log("Couldn't get petition JSON - " + textStatus + ": " + errorThrown);
        },
        success: function(petitionJson, _textStatus, _jqXHR) {
          var petitionData;
          petitionData = new PetitionData(petitionJson);
          setupTitle(petitionData);
          window.chart = new Chart(petitionData);
          return window.chart.draw();
        }
      });
    }
  });

}).call(this);
