// Generated by CoffeeScript 1.9.3
(function() {
  var Chart, setupTitle,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Chart = (function() {
    var TOP;

    TOP = 10;

    function Chart(petition_json) {
      this.petition_json = petition_json;
      this.draw = bind(this.draw, this);
      this.maxCountryFrequency = bind(this.maxCountryFrequency, this);
      this.signaturesByCountryDescendingCount = bind(this.signaturesByCountryDescendingCount, this);
      this.signaturesByCountry = bind(this.signaturesByCountry, this);
    }

    Chart.prototype.signaturesByCountry = function() {
      return this.petition_json.data.attributes.signatures_by_country.filter(function(country) {
        return country.code !== 'GB';
      });
    };

    Chart.prototype.signaturesByCountryDescendingCount = function() {
      var descending;
      descending = this.signaturesByCountry().sort(function(prev, current) {
        if (current.signature_count > prev.signature_count) {
          return 1;
        } else {
          return -1;
        }
      });
      return descending.slice(0, +(TOP - 1) + 1 || 9e9);
    };

    Chart.prototype.maxCountryFrequency = function() {
      return this.signaturesByCountryDescendingCount()[0].signature_count;
    };

    Chart.prototype.draw = function() {
      var bar, barWidth, countryLabels, data, height, margin, signaturesByCountry, svg, width, x, xAxis, y, yAxis;
      margin = {
        top: 40,
        right: 70,
        bottom: 150,
        left: 70
      };
      width = window.innerWidth - margin.left - margin.right;
      height = 550 - margin.top - margin.bottom;
      signaturesByCountry = this.signaturesByCountryDescendingCount();
      data = signaturesByCountry.map(function(country) {
        return country.signature_count;
      });
      countryLabels = signaturesByCountry.map(function(country) {
        return country.code;
      });
      barWidth = width / data.length;
      x = d3.scale.ordinal().domain(countryLabels).rangeBands([0, width]);
      y = d3.scale.linear().domain([0, this.maxCountryFrequency()]).range([height, 0]);
      xAxis = d3.svg.axis().scale(x).orient("bottom");
      yAxis = d3.svg.axis().scale(y).orient("left");
      svg = d3.select("#chart").append("svg").attr("width", width + margin.left + margin.right).attr("height", height + margin.top + margin.bottom).append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");
      svg.append("g").attr("class", "x axis").attr("transform", "translate(0," + height + ")").call(xAxis).selectAll("text").attr("transform", "rotate(90)").attr("x", 15).attr("y", 0).style("text-anchor", "start");
      svg.append("g").attr("class", "y axis").call(yAxis).append("text").attr("transform", "rotate(-90)").attr("y", -63).attr("dy", ".71em").style("text-anchor", "end").text("Signatures");
      bar = svg.selectAll(".bar").data(data).enter().append("rect").attr("class", "bar").attr("width", barWidth - 1).attr("height", function(d) {
        return height - y(d);
      }).attr("x", function(d, i) {
        return i * barWidth;
      }).attr("y", function(d) {
        return y(d);
      });
      return bar.append("rect");
    };

    return Chart;

  })();

  setupTitle = function(countries) {
    var c, formattedSignatureCount, uk;
    uk = ((function() {
      var j, len, results;
      results = [];
      for (j = 0, len = countries.length; j < len; j++) {
        c = countries[j];
        if (c.code === 'GB') {
          results.push(c);
        }
      }
      return results;
    })())[0];
    formattedSignatureCount = uk.signature_count.toLocaleString('en-GB', {
      minimumFractionDigits: 0
    });
    return $('.uk-signatures').text("(" + formattedSignatureCount + " signatures)");
  };

  jQuery(function() {
    if (document.getElementById('chart')) {
      return $.ajax({
        url: "https://petition.parliament.uk/petitions/171928.json",
        dataType: "json",
        error: function(jqXHR, textStatus, errorThrown) {
          return console.log("Couldn't get petition JSON - " + textStatus + ": " + errorThrown);
        },
        success: function(petitionData, _textStatus, _jqXHR) {
          setupTitle(petitionData.data.attributes.signatures_by_country);
          window.chart = new Chart(petitionData);
          return window.chart.draw();
        }
      });
    }
  });

}).call(this);
