// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.PageManager = (function() {
    var currentToShowValue;

    function PageManager(petitionUrl) {
      this.petitionUrl = petitionUrl;
      this.switchToSelectedUkNonUk = bind(this.switchToSelectedUkNonUk, this);
      this.setupCsvDownload = bind(this.setupCsvDownload, this);
      this.downloadConstituencyCsv = bind(this.downloadConstituencyCsv, this);
      this.downloadCountryCsv = bind(this.downloadCountryCsv, this);
      this.setupTitle = bind(this.setupTitle, this);
      this.setupToShowButtons = bind(this.setupToShowButtons, this);
      this.setupUkNonUkButtons = bind(this.setupUkNonUkButtons, this);
      this.setupUkSummary = bind(this.setupUkSummary, this);
      this.setupNonUkSummary = bind(this.setupNonUkSummary, this);
      this.setupProgressBar = bind(this.setupProgressBar, this);
      this.setupSubtitle = bind(this.setupSubtitle, this);
      this.setup = bind(this.setup, this);
      this.createOrReplaceChart = bind(this.createOrReplaceChart, this);
    }

    PageManager.prototype.createOrReplaceChart = function() {
      var data, slicedData, xAxisLabels;
      if (window._chart) {
        window._chart.replace();
      }
      if (this.ukNonUk() === 'uk') {
        slicedData = this.petitionData.signaturesByConstituencyDescendingCount({
          top: currentToShowValue()
        });
      } else {
        slicedData = this.petitionData.signaturesByCountryDescendingCount({
          filter: 'GB',
          top: currentToShowValue()
        });
      }
      xAxisLabels = slicedData.map(function(area) {
        return area.name;
      });
      data = slicedData.map(function(area) {
        return area.signature_count;
      });
      window._chart = new Chart(data, xAxisLabels, {
        toShow: currentToShowValue()
      });
      return window._chart.draw();
    };

    PageManager.prototype.setup = function() {
      return $.ajax({
        url: this.petitionUrl,
        dataType: "json",
        error: function(jqXHR, textStatus, errorThrown) {
          return console.log("Couldn't get petition JSON - " + textStatus + ": " + errorThrown);
        },
        success: (function(_this) {
          return function(petitionJson) {
            _this.petitionData = new PetitionData(petitionJson);
            _this.setupTitle();
            _this.setupSubtitle();
            _this.setupProgressBar();
            _this.setupToShowButtons();
            _this.setupUkNonUkButtons();
            _this.setupNonUkSummary();
            _this.setupCsvDownload();
            _this.setupUkSummary();
            return _this.createOrReplaceChart(currentToShowValue());
          };
        })(this)
      });
    };

    PageManager.prototype.setupSubtitle = function() {
      return $('.subtitle .n').text(this.petitionData.stats().total.toLocaleString('en-GB', {
        minimumFractionDigits: 0
      }));
    };

    PageManager.prototype.setupProgressBar = function() {
      var stats, wereAre;
      stats = this.petitionData.stats();
      wereAre = this.petitionData.state() === 'open' ? 'are' : 'were';
      $('.progress-bar-uk').attr('style', "width: " + (stats.percentage_uk.toFixed(1)) + "%");
      $('.progress-bar-uk span').text((stats.uk_total.toLocaleString('en-GB', {
        minimumFractionDigits: 0
      })) + " (" + (stats.percentage_uk.toFixed(1)) + "%) " + wereAre + " from the UK.");
      return $('.were-are').text(wereAre);
    };

    PageManager.prototype.setupNonUkSummary = function() {
      var stats;
      stats = this.petitionData.stats();
      $('.non-uk-summary .country-count').text(stats.non_uk_country_count);
      $('.non-uk-summary .slice-n').text(currentToShowValue());
      $('.non-uk-summary .n').text("" + (stats.international_total.toLocaleString('en-GB', {
        minimumFractionDigits: 0
      })));
      return $('.non-uk-summary .percent').text((stats.percentage_international.toFixed(1)) + "%");
    };

    PageManager.prototype.setupUkSummary = function() {
      var stats;
      stats = this.petitionData.stats();
      return $('.uk .constituency-count').text(stats.uk_constituency_count);
    };

    currentToShowValue = function() {
      return parseInt($('button.to-show.active').attr('data-to-show'));
    };

    PageManager.prototype.setupUkNonUkButtons = function() {
      return $('.uk-non-uk .dropdown-menu a').click((function(_this) {
        return function(e) {
          var selectedMenuItem;
          $('.uk-non-uk .dropdown-menu li').removeClass('disabled');
          selectedMenuItem = $(e.currentTarget);
          selectedMenuItem.parent('li').addClass('disabled');
          $('.uk-non-uk .inline-label').text(selectedMenuItem.text());
          return _this.switchToSelectedUkNonUk();
        };
      })(this));
    };

    PageManager.prototype.setupToShowButtons = function() {
      return $('button.to-show').click((function(_this) {
        return function(e) {
          var toShow;
          $('button.to-show').removeClass('active');
          toShow = parseInt($(e.currentTarget).addClass('active').attr('data-to-show'));
          _this.createOrReplaceChart(toShow);
          return _this.setupNonUkSummary();
        };
      })(this));
    };

    PageManager.prototype.setupTitle = function() {
      $('.petition-title').text('');
      $('.petition-title a').remove();
      $('.petition-title').append('<a />');
      $('.petition-title a').text((this.petitionData.title()) + " ").attr('href', this.petitionData.url());
      return $('.petition-title').append("<span class='badge " + (this.petitionData.state()) + "'>" + (this.petitionData.state().capitalizeFirstLetter()) + "</span>");
    };

    PageManager.prototype.downloadCountryCsv = function() {
      var country, csv, encodedUri, i, index, len, row, signaturesByCountry;
      signaturesByCountry = this.petitionData.signaturesByCountryDescendingCount({
        filter: 'NONE'
      });
      csv = "data:text/csv;charset=utf-8,country_code, country_name, signature_count\n";
      for (index = i = 0, len = signaturesByCountry.length; i < len; index = ++i) {
        country = signaturesByCountry[index];
        row = [country.code, "\"" + country.name + "\"", country.signature_count].join(",");
        csv += row;
        if (index < signaturesByCountry.length) {
          csv += "\n";
        }
      }
      encodedUri = encodeURI(csv);
      return window.open(encodedUri);
    };

    PageManager.prototype.downloadConstituencyCsv = function() {
      var constituency, csv, encodedUri, i, index, len, row, signaturesByConstituency;
      signaturesByConstituency = this.petitionData.signaturesByConstituencyDescendingCount();
      csv = "data:text/csv;charset=utf-8,name,ons_code,mp,signature_count\n";
      for (index = i = 0, len = signaturesByConstituency.length; i < len; index = ++i) {
        constituency = signaturesByConstituency[index];
        row = ["\"" + constituency.name + "\"", constituency.ons_code, constituency.mp, constituency.signature_count].join(",");
        csv += row;
        if (index < signaturesByConstituency.length) {
          csv += "\n";
        }
      }
      encodedUri = encodeURI(csv);
      return window.open(encodedUri);
    };

    PageManager.prototype.setupCsvDownload = function() {
      return $('#download').unbind('click').click((function(_this) {
        return function() {
          if (_this.ukNonUk() === 'uk') {
            return _this.downloadConstituencyCsv();
          } else {
            return _this.downloadCountryCsv();
          }
        };
      })(this));
    };

    PageManager.prototype.toggleSubtitleVisibility = function() {
      var hidingClass, nowCurrent, showingClass;
      nowCurrent = this.ukNonUk();
      showingClass = "." + nowCurrent;
      hidingClass = nowCurrent === 'uk' ? '.non-uk' : '.uk';
      $(showingClass).removeClass('hidden');
      return $(hidingClass).addClass('hidden');
    };

    PageManager.prototype.ukNonUk = function() {
      return $('.uk-non-uk li.disabled a').text().toLowerCase();
    };

    PageManager.prototype.switchToSelectedUkNonUk = function() {
      this.toggleSubtitleVisibility();
      this.setupCsvDownload();
      return this.createOrReplaceChart();
    };

    return PageManager;

  })();

}).call(this);

//# sourceMappingURL=pageManager.js.map
