// Generated by CoffeeScript 1.9.3
(function() {
  var setupDropdown;

  setupDropdown = function(petitionsJson, petitionUrlClicked) {
    var appendPetitionItem, i, len, petition, petitionsMenu, ref;
    petitionsMenu = $('.petitions.dropdown-menu').empty();
    appendPetitionItem = function(petitionJson) {
      return petitionsMenu.append("<li>\n  <a\n    data-petition-url='" + petitionJson.links.self + "'\n    href='#'>" + petitionJson.attributes.action + "</a>\n</li>");
    };
    ref = petitionsJson.data;
    for (i = 0, len = ref.length; i < len; i++) {
      petition = ref[i];
      appendPetitionItem(petition);
    }
    return petitionsMenu.find('li a').click(function(e) {
      var url;
      url = $(e.currentTarget).attr('data-petition-url');
      return petitionUrlClicked(url);
    });
  };

  jQuery(function() {
    if (document.getElementById('drpPetitions')) {
      return $.ajax({
        url: "https://petition.parliament.uk/petitions.json",
        dataType: "json",
        error: function(jqXHR, textStatus, errorThrown) {
          return console.log("Couldn't get petitions JSON - " + textStatus + ": " + errorThrown);
        },
        success: function(petitionsJson, _textStatus, _jqXHR) {
          return setupDropdown(petitionsJson, function(url) {
            return PageManager.setup(url);
          });
        }
      });
    }
  });

}).call(this);

//# sourceMappingURL=petitionsData.js.map
