// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.PetitionData = (function() {
    var FILTER, TOP;

    TOP = 25;

    FILTER = 'GB';

    function PetitionData(petitionJson) {
      this.petitionJson = petitionJson;
      this.maxCountryFrequency = bind(this.maxCountryFrequency, this);
      this.signaturesByCountryDescendingCount = bind(this.signaturesByCountryDescendingCount, this);
      this.uk = bind(this.uk, this);
      this.signaturesByCountry = bind(this.signaturesByCountry, this);
      this.url = bind(this.url, this);
      this.title = bind(this.title, this);
    }

    PetitionData.prototype.title = function() {
      return this.petitionJson.data.attributes.action;
    };

    PetitionData.prototype.url = function() {
      return this.petitionJson.links.self.replace('.json', '');
    };

    PetitionData.prototype.signaturesByCountry = function(options) {
      if (options == null) {
        options = {
          filter: FILTER
        };
      }
      return this._signaturesByCountry = this.petitionJson.data.attributes.signatures_by_country.filter(function(country) {
        return country.code !== options.filter;
      });
    };

    PetitionData.prototype.signatureCountForName = function(name) {
      return this.signaturesByCountry().find(function(c) {
        return c.name === name;
      }).signature_count;
    };

    PetitionData.prototype.uk = function() {
      var c, countries;
      countries = this.petitionJson.data.attributes.signatures_by_country;
      return ((function() {
        var i, len, results;
        results = [];
        for (i = 0, len = countries.length; i < len; i++) {
          c = countries[i];
          if (c.code === 'GB') {
            results.push(c);
          }
        }
        return results;
      })())[0];
    };

    PetitionData.prototype.signaturesByCountryDescendingCount = function(options) {
      var descending;
      if (options == null) {
        options = {
          top: TOP,
          filter: FILTER
        };
      }
      descending = this.signaturesByCountry({
        filter: options.filter
      }).sort(function(prev, current) {
        if (current.signature_count > prev.signature_count) {
          return 1;
        } else {
          return -1;
        }
      });
      return descending.slice(0, +(options.top - 1) + 1 || 9e9);
    };

    PetitionData.prototype.maxCountryFrequency = function() {
      return this.signaturesByCountryDescendingCount()[0].signature_count;
    };

    return PetitionData;

  })();

}).call(this);
