// Generated by CoffeeScript 1.9.3
(function() {
  var setupDropdown;

  setupDropdown = function(petitionsJson) {
    var appendPetitionItem, i, len, petition, petitionsMenu, ref, results;
    petitionsMenu = $('.petitions.dropdown-menu');
    appendPetitionItem = function(petitionJson) {
      var petitionUrl;
      petitionUrl = new PetitionUrl(petitionJson.links.self);
      return petitionsMenu.append("<li>\n  <a href='#/petitions/" + petitionUrl.petitionId + "'>" + petitionJson.attributes.action + "</a>\n</li>");
    };
    ref = petitionsJson.data;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      petition = ref[i];
      results.push(appendPetitionItem(petition));
    }
    return results;
  };

  jQuery(function() {
    if (document.getElementById('drpPetitions')) {
      return $.ajax({
        url: "https://petition.parliament.uk/petitions.json",
        dataType: "json",
        error: function(jqXHR, textStatus, errorThrown) {
          return console.log("Couldn't get petitions JSON - " + textStatus + ": " + errorThrown);
        },
        success: function(petitionsJson) {
          return setupDropdown(petitionsJson, function(url) {
            return window._pageManager.setup(url);
          });
        }
      });
    }
  });

}).call(this);

//# sourceMappingURL=petitionsData.js.map
