// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.PetitionUrl = (function() {
    var PETITION_URL_REGEX;

    PETITION_URL_REGEX = /https:\/\/petition\.parliament\.uk\/petitions\/([0-9]+)(?:.json)?/;

    function PetitionUrl(idOrUrl) {
      this.toString = bind(this.toString, this);
      this.ourUrl = bind(this.ourUrl, this);
      var match;
      if (match = idOrUrl.match(PETITION_URL_REGEX)) {
        this.petitionId = match[1];
        this.petitionUrl = idOrUrl;
      } else if (idOrUrl.match(/[0-9]/)) {
        this.petitionUrl = "https://petition.parliament.uk/petitions/" + idOrUrl + ".json";
        this.petitionId = idOrUrl;
      } else {
        throw idOrUrl + " is neither an ID nor a URL";
      }
    }

    PetitionUrl.prototype.ourUrl = function() {
      return "#/petitions/" + this.petitionId;
    };

    PetitionUrl.prototype.toString = function() {
      return this.petitionUrl;
    };

    return PetitionUrl;

  })();

}).call(this);

//# sourceMappingURL=petitionUrl.js.map
